In [3]:
import numpy as np

# THe Basics

In [27]:
a =np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
b =np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
# Get dimension
b.ndim

2

In [15]:
a.ndim

1

In [12]:
#Get Shape
a.shape

(3,)

In [13]:
b.shape

(2, 3)

In [14]:
#Get type
a.dtype

dtype('int32')

In [16]:
#Get size
a.itemsize

4

In [17]:
b.itemsize

8

In [18]:
#get total size
a.nbytes

12

# Acceess, changing specific elements

In [4]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)
    
    
    


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
#Get a specific element [r,c]
c[1,5]

13

In [6]:
#get a specific row
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
#get a specific column
c[:,2]

array([ 3, 10])

In [8]:
#get a little fancy [start index:end index:stepsize]
c[0,1:-1:2]

array([2, 4, 6])

In [47]:
c[1,5]= 100

c[1,:]=[1]
c[:,2]=[99,98]
print(c)

[[ 1  2 99  4  5  6  7]
 [ 1  1 98  1  1  1  1]]


In [48]:
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [50]:
#get the specific elements
d[0,1,1]

4

In [54]:
#replace
d[0,0,:]=[11,12]
d[0,:,:]=[[99,98]]
print(d)

[[[99 98]
  [99 98]]

 [[ 5  6]
  [ 7  8]]]


# initialising different type of array

In [55]:
#all 0 matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
#all 1
np.ones((4,2,2),dtype= 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [57]:
# any other number(full_like) it will be used when we are using b
np.full_like(b,4)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [59]:
np.full(b.shape,4) # only full will be used when b.shapa we are using

array([[4, 4, 4],
       [4, 4, 4]])

In [61]:
 #Random decimal numbers
np.random.rand(4,2,3)

array([[[0.93114218, 0.64981343, 0.23923774],
        [0.41713287, 0.29377211, 0.35164579]],

       [[0.8035905 , 0.23904113, 0.04134911],
        [0.98637611, 0.60989114, 0.62495544]],

       [[0.56840578, 0.67221192, 0.07061988],
        [0.03286908, 0.8168203 , 0.9072579 ]],

       [[0.98481223, 0.78565145, 0.41103484],
        [0.33210339, 0.16932766, 0.30613464]]])

In [63]:
np.random.random_sample(b.shape)

array([[0.51027251, 0.02298717, 0.63057615],
       [0.17103754, 0.74420412, 0.16081661]])

In [65]:
# random integer values
np.random.randint(-4,8,size = (3,3))
    

array([[ 1, -3,  7],
       [ 4,  6,  1],
       [ 4, -2,  2]])

In [66]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,4,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [9]:
# Repeat an arrayn    here 4 means the numbers will be repeated 4 times.
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,4,axis=1)
print(r1)

[[1 1 1 1 2 2 2 2 3 3 3 3]]


In [75]:
output = np.ones((5,5))
print(output)

z= np.zeros((3,3))
print(z)
z[1,1]=9
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [76]:
output[1:4,1:4]=z # also can be written as output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### BE careful when copying arrays!!!!

In [78]:
a= np.array([1,2,3]) # here both a an b are changing but if we want to change b only
b= a
b[0]=100
print(b)

print(a)

[100   2   3]
[100   2   3]


In [80]:
a= np.array([1,2,3]) # means we can use .copy()
b= a.copy()
b[0]=100
print(b)
print(a)

[100   2   3]
[1 2 3]


## Mathematics

In [81]:
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [82]:
a+2

array([3, 4, 5, 6])

In [83]:
a-2

array([-1,  0,  1,  2])

In [84]:
a*2

array([2, 4, 6, 8])

In [85]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [86]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [87]:
a**2

array([ 1,  4,  9, 16])

In [88]:
#take the sin of all value # remember while taking sin ,cos or any trigonometric value we need to use  np.sin(a)
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [89]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear algebra

In [95]:
a= np.ones((2,3))
print(a)
b= np.full((3,2),2)
print(b)
#a*b it will give error
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [98]:
aa= np.array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])
print(aa)
abs(aa)

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


array([0.54030231, 0.41614684, 0.9899925 , 0.65364362])

In [100]:
r= np.linspace(2,10,3) # when we are using linspace and last value in bracket means that number of terms should be there
print(r)

[ 2.  6. 10.]
